-- No-op.
-- This migration originally altered "MenuItemSubstitute" before that table
-- existed in migration history, which breaks shadow DB replay.
-- The table is introduced later in 20260324000000_add_modifiers_addons_substitutes.
-- Keeping this migration as a no-op preserves migration ordering.